name: logger
description: ...
version: 0.0.0
#repository: https://github.com/rtmigo/tabular

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: any
  stack_trace: ^1.10.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
